---
title: "RESPOND Detailed Site Reports"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

<br>

## [Los Angeles County - 80](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Los\ Angeles\ County.80.html)

## [Northern CA - 30](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Northern CA.30.html)

## [Greater CA - 10](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Greater CA.10.html)

## [Detroit - 60](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Detroit.60.html)

## [Louisiana - 40](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Louisiana.40.html)

## [Georgia - 20](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Georgia.20.html)

## [Michigan - 61](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Michigan.61.html)

## [New Jersey - 50](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.New Jersey.50.html)

## [Texas - 70](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.Texas.70.html)

## [WebRecruit - 99](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.WebRecruit.99.html)

## [USC Other - 81](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.USC Other.81.html)

## [USC MEC - 82](InitalDataCleaning/Survey\ report/Scantron\ data/Cleaning\ Report\ 12072021/SurveyOnly\ cleaning\ report.USC MEC.82.html)

<br>

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}

library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
library(here)
library(fs)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")
```


<br>
<br>